feat(ci): check other files for executable permissions, check .sh syntax with a linter

diff --git a/.github/workflows/fileChecks.yml b/.github/workflows/fileChecks.yml
--- a/.github/workflows/fileChecks.yml
+++ b/.github/workflows/fileChecks.yml
@@ -39,6 +39,39 @@ jobs:
     - name: Success (if no failed files)
       if: ${{ env.failed_apps == '0' }} 
       run: echo "All .bin files have executable permissions (or no .bin files found)."
+
+  check_bin_permissions:
+    name: executables-project-filecheck
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - uses: actions/setup-python@v5
+
+    - name: Install dependencies (if any)
+      run: |
+        python3 -m pip install --upgrade pip
+ 
+
+    - name: Check apps
+      id: run_script_apps
+      run: |
+        python3 ci_tools/executable-check.py > output_apps.txt
+        echo "failed_apps=$(grep -c " - " output_apps.txt)" >> $GITHUB_ENV
+      env:
+        # Replace with the directory you want to check
+        DIRECTORY_TO_CHECK: images/makeproject/project/bin
+
+    - name: Check for failed files
+      if: ${{ env.failed_apps != '0' }} 
+      run: |
+        echo "::error title=Missing executable permissions::Found .bin files without executable permissions.  See output for details."
+        cat output.txt
+        exit 1
+ 
+
+    - name: Success (if no failed files)
+      if: ${{ env.failed_apps == '0' }} 
+      run: echo "All .bin files have executable permissions (or no .bin files found)."
   
   check_versionxml:
     name: check_versions
@@ -73,9 +106,18 @@ jobs:
         if: ${{ env.failed_xml == '0' }} 
         run: echo "All version.xml files look correct (or we did not find any)."
 
-  lint:
+  py_lint:
     name: check_python_syntax
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: cclauss/Find-Python-syntax-errors-action@master
+
+  sh_lint:
+    name: check_shell_syntax
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Run ShellCheck
+        uses: Azbagheri/shell-linter@latest
